# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
